# Generated by Django 5.0.4 on 2024-05-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maseru_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaseruStaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.DeleteModel(
            name='MaseruPatientModel',
        ),
    ]
